backend:
  name: test-repo
  branch: main

media_folder: "src/images/uploads"
public_folder: "/images/uploads"
media_library:
  name: uploadcare

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "src/index.njk"
        label: "Homepage Content"
        name: "home"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Hero Message", name: "hero", widget: "text" }
